spring:
    application:
        name: uniclub

    config:
        import: "optional:file:.env[.properties]"
    datasource:
        url: jdbc:mysql://localhost:${MYSQL_PORT}/${MYSQL_DATABASE}
        username: ${MYSQL_USER}
        password: ${MYSQL_PASSWORD}

    jpa:
        generate-ddl: true
        hibernate:
            ddl-auto: validate

    devtools:
        restart:
            enabled: true
    servlet:
        multipart:
            max-file-size: 500MB
            max-request-size: 500MB
server:
    address: localhost
    port: 8080
jwt:
    private-key: LTKw1Ba/s6nM6PoClDdEwk68UZ7cMBuqNGARAGIFowU=

path:
    upload: ${USERPROFILE}/Downloads/spring_upload
